---
title: "Getting started with mdatools for R"
author: "Sergey Kucheryavskiy"
date: "16 August 2016"
knit: bookdown::render_book 
site: bookdown::bookdown_site
output: 
   bookdown::gitbook:
      split_by: section
documentclass: book
github-repo: svkucheryavski/mdatools.bookdown
description: "This is a user guide for mdatools — R package for preprocessing, exploring and analysis of multivariate data. The package provides methods mostly common for Chemometrics. The general idea of the package is to collect most of the common chemometric methods and give a similar user interface for using them. So if a user knows how to make a model and visualise results for one method, he or she can easily do this for the others."
---

# Introduction {-}

This is a user guide for _mdatools_ — R package for preprocessing, exploring and analysis of multivariate data. The package provides methods mostly common for [Chemometrics](http://en.wikipedia.org/wiki/Chemometrics). The general idea of the package is to collect the popular chemometric methods and give a similar "user interface" for using them. So if a user knows how to make a model and visualize results for one method, he or she can easily do this for the other methods as well.

I decided to rewrite this tutorial in order to add more details and examples for the implemented methods. This is a pre-release version and I am still working on it. Also when new version of the package is released, there will be some changes/additions to the tutorial as well. You can track main changes in the text [here][What is new].

All methods implemented in the package were tested using well-known datasets. However, there still could be some bugs, in this case please report to [svkucheryavski@gmail.com](/mailto:svkucheryavski@gmail.com) or use [Issues tool](https://github.com/svkucheryavski/mdatools/issues) at GitHub. You are also very welcome to share your  comments and suggestions about the package functionality.

