# What is new {-#news}

**23.04.2021**

Added description of new features added in v. 0.11.4:

* using test set validation in [iPLS](#ipls).
* possibility to force selected contribution and spectral values in [MCR-ALS](#mcr--als).
* added information about how to provide user defined indices for pure variables in [Purity method](#mcr--purity)
* added link to relevant paper in the [PCA model complexity](#pca--model-complexity) section

**22.01.2021**

* added section about [Procrustes cross-validation](#pca--pcv) for PCA, which was recently added to the package (v. 0.11.3).

**23.07.2020**

* section about [MCR Purity method](#mcr--purity) has been re-written to correspond to the algorithm changes in v. 0.11.1.

**12.07.2020**

* added chapters about [MCR methods](#mcr) implemented in v. 0.11.0.
* added [description](#prep--alsbasecorr) of new preprocessing methods `prep.alsbasecorr()`
* several small improvements in text

**02.03.2020**

* fixed a code typo in chapter about outlier detection in PLS.

**01.03.2020**

Small changes related to v. 0.10.1:

* added description of density plots
* added description of `plotHotellingEllipse()` method to PCA chapter


**29.01.2020**

The new version of the package (0.10.0) has a lot of changes and improvements, so it was decided
to update the book to a large degree. In addition to that, chapters about [iPLS](#ipls) and [randomization tests](#pls--randomization-test) have been added as well as information on new tools. See [list of changes](https://github.com/svkucheryavski/mdatools/blob/master/NEWS.md) in the package for more details.

**9.11.2018**

* new minor version (0.9.2) of package is available via GitHub with several bug fixes
* added text about `max.cov` parameter in [Preprocessing](#datasets--preprocessing) chapter.

**5.07.2018**

* new chapter about [PLS-DA](#plsda)
* small improvements and corrections to text of other chapters
* added a short description if new `opacity` parameter for `mdaplot()` method

**3.04.2018**

* new chapter about [randomized PCA algorithms](#pca--randomized-algorithm)
* new chapter about [critical limits for distances in PCA/SIMCA](#pca--distances-and-limits)
* chapter for SIMCA has been updated with description of new methods
* added a short text about new properties for `plotPredictions()` method in PLS
* small corrections and improvements

**23.11.2017**

* corrections in SIMCA part of documentation about using test set

**03.08.2017**

* several minor versions has been released since the last book update (0.8.1-0.8.4)
* new text describes how to use `summary()` for regression coefficients
* text about `getRegcoeffs().pls` has been updated
* some updates in plans (see section above)

**30.10.2016**

* fixed a bug in PCA when explained variance was calculated incorrectly for data with excluded rows
* fixed several issues with SIMCA (cross-validation) and SIMCAM (Cooman's plot)
* added a chapter about SIMCA to the tutorial

**14.10.2016**

The new version (0.8.0) brings a lot of new features, therefore it was decided to rewrite this tutorial
completely and start this log from the scratch. Most of the things available in the previous version
of the package will work without any changes. But if you have been using functions `mdaplot()`
and `mdaplotg()` it makes sense to read how the new implementation works and rewrite your code.
The use of plotting tools became much simpler and more efficient. The main changes in the package are:

* added a possibility to assign specific attributes to datasets, which makes plotting easier.
* added a possibility to exclude (hide) selected rows and columns when create a model.
* if a data frame has factor columns they will be automatically converted to a set of dummy variables.
* added several functions to make the operations with datasets containing specific attributes easier.
* plotting tools (`mdaplot()`, `mdaplotg()`) were rewritten to make the use of them easier and more efficient
* scores and loadings plots now show a percent of explained variance
* biplot is now available for PCA models (`plotBiplot`)
* added support for images, see a [specific chapter][Working with images] for details
* cross-validation procedures were optimized for most of the methods and now takes less time
* several bug fixes and small improvements

