<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>0.1 Forward iPLS | Getting started with mdatools for R</title>
  <meta name="description" content="This is a user guide for mdatools — R package for preprocessing, exploring and analysis of multivariate data. The package provides methods mostly common for Chemometrics. The general idea of the package is to collect most of the common chemometric methods and give a similar user interface for using them. So if a user knows how to make a model and visualise results for one method, he or she can easily do this for the others." />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="0.1 Forward iPLS | Getting started with mdatools for R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a user guide for mdatools — R package for preprocessing, exploring and analysis of multivariate data. The package provides methods mostly common for Chemometrics. The general idea of the package is to collect most of the common chemometric methods and give a similar user interface for using them. So if a user knows how to make a model and visualise results for one method, he or she can easily do this for the others." />
  <meta name="github-repo" content="svkucheryavski/mdatools.bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="0.1 Forward iPLS | Getting started with mdatools for R" />
  
  <meta name="twitter:description" content="This is a user guide for mdatools — R package for preprocessing, exploring and analysis of multivariate data. The package provides methods mostly common for Chemometrics. The general idea of the package is to collect most of the common chemometric methods and give a similar user interface for using them. So if a user knows how to make a model and visualise results for one method, he or she can easily do this for the others." />
  

<meta name="author" content="Sergey Kucheryavskiy" />


<meta name="date" content="2020-01-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="interval-pls.html"/>
<link rel="next" href="backward-ipls.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="what-is-new.html"><a href="what-is-new.html"><i class="fa fa-check"></i>What is new</a>
<ul>
<li class="chapter" data-level="" data-path="what-is-new.html"><a href="what-is-new.html#what-expect-from-future-releases"><i class="fa fa-check"></i>What expect from future releases</a></li>
<li class="chapter" data-level="" data-path="what-is-new.html"><a href="what-is-new.html#last-changes-and-improvements-to-book-and-package"><i class="fa fa-check"></i>Last changes and improvements to book and package</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="overview.html"><a href="overview.html"><i class="fa fa-check"></i>Overview</a>
<ul>
<li class="chapter" data-level="" data-path="what-mdatools-can-do.html"><a href="what-mdatools-can-do.html"><i class="fa fa-check"></i>What mdatools can do?</a></li>
<li class="chapter" data-level="" data-path="how-to-install.html"><a href="how-to-install.html"><i class="fa fa-check"></i>How to install</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="datasets-and-plots.html"><a href="datasets-and-plots.html"><i class="fa fa-check"></i>Datasets and plots</a>
<ul>
<li class="chapter" data-level="" data-path="attributes-and-factors.html"><a href="attributes-and-factors.html"><i class="fa fa-check"></i>Attributes and factors</a>
<ul>
<li class="chapter" data-level="" data-path="attributes-and-factors.html"><a href="attributes-and-factors.html#package-specific-attributes"><i class="fa fa-check"></i>Package specific attributes</a></li>
<li class="chapter" data-level="" data-path="attributes-and-factors.html"><a href="attributes-and-factors.html#attributes-for-plots"><i class="fa fa-check"></i>Attributes for plots</a></li>
<li class="chapter" data-level="" data-path="attributes-and-factors.html"><a href="attributes-and-factors.html#special-methods-for-data-transformations"><i class="fa fa-check"></i>Special methods for data transformations</a></li>
<li class="chapter" data-level="" data-path="attributes-and-factors.html"><a href="attributes-and-factors.html#data-frames-with-factors"><i class="fa fa-check"></i>Data frames with factors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="simple-plots.html"><a href="simple-plots.html"><i class="fa fa-check"></i>Simple plots</a>
<ul>
<li class="chapter" data-level="" data-path="simple-plots.html"><a href="simple-plots.html#scatter-plots"><i class="fa fa-check"></i>Scatter plots</a></li>
<li class="chapter" data-level="" data-path="simple-plots.html"><a href="simple-plots.html#line-plots"><i class="fa fa-check"></i>Line plots</a></li>
<li class="chapter" data-level="" data-path="simple-plots.html"><a href="simple-plots.html#bar-and-errorbar-plots"><i class="fa fa-check"></i>Bar and errorbar plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="plots-for-groups-of-objects.html"><a href="plots-for-groups-of-objects.html"><i class="fa fa-check"></i>Plots for groups of objects</a>
<ul>
<li class="chapter" data-level="" data-path="plots-for-groups-of-objects.html"><a href="plots-for-groups-of-objects.html#one-matrix-or-data-frame"><i class="fa fa-check"></i>One matrix or data frame</a></li>
<li class="chapter" data-level="" data-path="plots-for-groups-of-objects.html"><a href="plots-for-groups-of-objects.html#list-with-matrices-or-data-frames"><i class="fa fa-check"></i>List with matrices or data frames</a></li>
<li class="chapter" data-level="" data-path="plots-for-groups-of-objects.html"><a href="plots-for-groups-of-objects.html#use-factors-to-split-a-dataset-into-groups"><i class="fa fa-check"></i>Use factors to split a dataset into groups</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="working-with-images.html"><a href="working-with-images.html"><i class="fa fa-check"></i>Working with images</a></li>
<li class="chapter" data-level="" data-path="preprocessing.html"><a href="preprocessing.html"><i class="fa fa-check"></i>Preprocessing</a>
<ul>
<li class="chapter" data-level="" data-path="preprocessing.html"><a href="preprocessing.html#autoscaling"><i class="fa fa-check"></i>Autoscaling</a></li>
<li class="chapter" data-level="" data-path="preprocessing.html"><a href="preprocessing.html#correction-of-spectral-baseline"><i class="fa fa-check"></i>Correction of spectral baseline</a></li>
<li class="chapter" data-level="" data-path="preprocessing.html"><a href="preprocessing.html#smoothing-and-derivatives"><i class="fa fa-check"></i>Smoothing and derivatives</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html"><i class="fa fa-check"></i>Principal component analysis</a>
<ul>
<li class="chapter" data-level="" data-path="models-and-results.html"><a href="models-and-results.html"><i class="fa fa-check"></i>Models and results</a>
<ul>
<li class="chapter" data-level="" data-path="models-and-results.html"><a href="models-and-results.html#model-calibration"><i class="fa fa-check"></i>Model calibration</a></li>
<li class="chapter" data-level="" data-path="models-and-results.html"><a href="models-and-results.html#model-validation"><i class="fa fa-check"></i>Model validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="plotting-methods.html"><a href="plotting-methods.html"><i class="fa fa-check"></i>Plotting methods</a>
<ul>
<li class="chapter" data-level="" data-path="plotting-methods.html"><a href="plotting-methods.html#support-for-images"><i class="fa fa-check"></i>Support for images</a></li>
<li class="chapter" data-level="" data-path="plotting-methods.html"><a href="plotting-methods.html#manual-x-values-for-loading-line-plot"><i class="fa fa-check"></i>Manual x-values for loading line plot</a></li>
<li class="chapter" data-level="" data-path="plotting-methods.html"><a href="plotting-methods.html#excluding-rows-and-columns"><i class="fa fa-check"></i>Excluding rows and columns</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="residuals-and-critical-limits.html"><a href="residuals-and-critical-limits.html"><i class="fa fa-check"></i>Residuals and critical limits</a>
<ul>
<li class="chapter" data-level="" data-path="residuals-and-critical-limits.html"><a href="residuals-and-critical-limits.html#distance-to-model-and-score-distance"><i class="fa fa-check"></i>Distance to model and score distance</a></li>
<li class="chapter" data-level="" data-path="residuals-and-critical-limits.html"><a href="residuals-and-critical-limits.html#critical-limits"><i class="fa fa-check"></i>Critical limits</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="model-complexity.html"><a href="model-complexity.html"><i class="fa fa-check"></i>Model complexity</a></li>
<li class="chapter" data-level="" data-path="randomized-pca-algorithms.html"><a href="randomized-pca-algorithms.html"><i class="fa fa-check"></i>Randomized PCA algorithms</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="simcadd-simca-classification.html"><a href="simcadd-simca-classification.html"><i class="fa fa-check"></i>SIMCA/DD-SIMCA classification</a>
<ul>
<li class="chapter" data-level="" data-path="calibration-and-validation.html"><a href="calibration-and-validation.html"><i class="fa fa-check"></i>Calibration and validation</a>
<ul>
<li class="chapter" data-level="" data-path="calibration-and-validation.html"><a href="calibration-and-validation.html#cross-validation"><i class="fa fa-check"></i>Cross-validation</a></li>
<li class="chapter" data-level="" data-path="calibration-and-validation.html"><a href="calibration-and-validation.html#predictions-and-validation-with-a-test-set"><i class="fa fa-check"></i>Predictions and validation with a test set</a></li>
<li class="chapter" data-level="" data-path="calibration-and-validation.html"><a href="calibration-and-validation.html#class-belonging-probabilities"><i class="fa fa-check"></i>Class belonging probabilities</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multiclass-classification.html"><a href="multiclass-classification.html"><i class="fa fa-check"></i>Multiclass classification</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="partial-least-squares-regression.html"><a href="partial-least-squares-regression.html"><i class="fa fa-check"></i>Partial least squares regression</a>
<ul>
<li class="chapter" data-level="" data-path="models-and-results-1.html"><a href="models-and-results-1.html"><i class="fa fa-check"></i>Models and results</a>
<ul>
<li class="chapter" data-level="" data-path="models-and-results-1.html"><a href="models-and-results-1.html#model-calibration-1"><i class="fa fa-check"></i>Model calibration</a></li>
<li class="chapter" data-level="" data-path="models-and-results-1.html"><a href="models-and-results-1.html#model-validation-1"><i class="fa fa-check"></i>Model validation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="plotting-methods-1.html"><a href="plotting-methods-1.html"><i class="fa fa-check"></i>Plotting methods</a>
<ul>
<li class="chapter" data-level="" data-path="plotting-methods-1.html"><a href="plotting-methods-1.html#excluding-rows-and-columns-1"><i class="fa fa-check"></i>Excluding rows and columns</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="variable-selection.html"><a href="variable-selection.html"><i class="fa fa-check"></i>Variable selection</a></li>
<li class="chapter" data-level="" data-path="distances-and-outlier-detection.html"><a href="distances-and-outlier-detection.html"><i class="fa fa-check"></i>Distances and outlier detection</a>
<ul>
<li class="chapter" data-level="" data-path="distances-and-outlier-detection.html"><a href="distances-and-outlier-detection.html#residual-distance-for-x-decomposition"><i class="fa fa-check"></i>Residual distance for X-decomposition</a></li>
<li class="chapter" data-level="" data-path="distances-and-outlier-detection.html"><a href="distances-and-outlier-detection.html#residual-distance-for-y-decomposition-and-total-distance"><i class="fa fa-check"></i>Residual distance for Y-decomposition and total distance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="randomization-test.html"><a href="randomization-test.html"><i class="fa fa-check"></i>Randomization test</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="pls-discriminant-analysis.html"><a href="pls-discriminant-analysis.html"><i class="fa fa-check"></i>PLS Discriminant Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="calibration-of-pls-da-model.html"><a href="calibration-of-pls-da-model.html"><i class="fa fa-check"></i>Calibration of PLS-DA model</a></li>
<li class="chapter" data-level="" data-path="classification-plots.html"><a href="classification-plots.html"><i class="fa fa-check"></i>Classification plots</a></li>
<li class="chapter" data-level="" data-path="performance-plots.html"><a href="performance-plots.html"><i class="fa fa-check"></i>Performance plots</a></li>
<li class="chapter" data-level="" data-path="predictions-for-a-new-data.html"><a href="predictions-for-a-new-data.html"><i class="fa fa-check"></i>Predictions for a new data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="interval-pls.html"><a href="interval-pls.html"><i class="fa fa-check"></i>Interval PLS</a>
<ul>
<li class="chapter" data-level="0.1" data-path="forward-ipls.html"><a href="forward-ipls.html"><i class="fa fa-check"></i><b>0.1</b> Forward iPLS</a></li>
<li class="chapter" data-level="0.2" data-path="backward-ipls.html"><a href="backward-ipls.html"><i class="fa fa-check"></i><b>0.2</b> Backward iPLS</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Getting started with mdatools for R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="forward-ipls" class="section level2">
<h2><span class="header-section-number">0.1</span> Forward iPLS</h2>
<p>The forward approach works as follows</p>
<ol style="list-style-type: decimal">
<li>Split spectral data into <span class="math inline">\(N\)</span> intervals</li>
<li>Create an empty vector with selected intervals</li>
<li>Create a model where intervals in the vector (already slected) are combined with one of the rest. If combination improves the model, add the this new interval to the vector.</li>
<li>Repeat previous step until there is no improvements.</li>
</ol>
<p>Apparently when nothing is selected, on step 3, the algorithm simply create model for every interval available. As you can see iPLS is iterative procedure. If you have 20 intervals you need to create 20 models on the first step, 19 models on the second step and so on.</p>
<p>In <em>mdatools</em>, you can run iPLS selection by using function <code>ipls</code>. You have to specify matrix with predictors (<code>x</code>) and responses (<code>y</code>), number of components in global model (<code>glob.ncomp</code>), and define intervals. In addition to that you can also specify parameters of cross-validation (<code>cv</code>) as well as criterion for selection of optimal number of components (<code>ncomp.selcrit</code>) for local models similar to PLS. Forward iPLS is used as a default algorithm.</p>
<p>Intervals can be defined using one of the three parameters: either number of intervals (<code>int.num</code>), width of an interval (<code>int.width</code>) or specify start and end of each interval as a two-column matrix with variable indices (<code>int.limits</code>). In addition to that, you can specify maximum number of component for local models (<code>int.ncomp</code>) and maximum number of iterations — so method will stop regardless you have improvements or not (<code>int.niter</code>). By default the number of maximum itrations is limited to 30.</p>
<p>Here is an example of using iPLS for Simdata (for concentration of third chemical component, C3)using 30 intervals.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="forward-ipls.html#cb1-1"></a><span class="kw">data</span>(simdata)</span>
<span id="cb1-2"><a href="forward-ipls.html#cb1-2"></a>X =<span class="st"> </span>simdata<span class="op">$</span>spectra.c</span>
<span id="cb1-3"><a href="forward-ipls.html#cb1-3"></a>y =<span class="st"> </span>simdata<span class="op">$</span>conc.c[, <span class="dv">3</span>]</span>
<span id="cb1-4"><a href="forward-ipls.html#cb1-4"></a></span>
<span id="cb1-5"><a href="forward-ipls.html#cb1-5"></a>m =<span class="st"> </span><span class="kw">ipls</span>(X, y, <span class="dt">glob.ncomp =</span> <span class="dv">4</span>, <span class="dt">int.num =</span> <span class="dv">30</span>)</span></code></pre></div>
<pre><code>## 
## Model with all intervals: RMSECV = 0.005880, nLV = 3
## Iteration   1/ 30... selected interval   9 (RMSECV = 0.013965, nLV = 2)
## Iteration   2/ 30... selected interval  13 (RMSECV = 0.006588, nLV = 3)
## Iteration   3/ 30... selected interval  21 (RMSECV = 0.006106, nLV = 3)
## Iteration   4/ 30... selected interval   7 (RMSECV = 0.006002, nLV = 3)
## Iteration   5/ 30... selected interval   5 (RMSECV = 0.005957, nLV = 3)
## Iteration   6/ 30... selected interval  22 (RMSECV = 0.005920, nLV = 3)
## Iteration   7/ 30... selected interval  19 (RMSECV = 0.005898, nLV = 3)
## Iteration   8/ 30... selected interval  12 (RMSECV = 0.005864, nLV = 3)
## Iteration   9/ 30... selected interval  11 (RMSECV = 0.005837, nLV = 3)
## Iteration  10/ 30... selected interval  20 (RMSECV = 0.005824, nLV = 3)
## Iteration  11/ 30... selected interval  26 (RMSECV = 0.005819, nLV = 3)
## Iteration  12/ 30... selected interval   1 (RMSECV = 0.005815, nLV = 3)
## Iteration  13/ 30... selected interval  14 (RMSECV = 0.005811, nLV = 3)
## Iteration  14/ 30... selected interval  27 (RMSECV = 0.005807, nLV = 3)
## Iteration  15/ 30... selected interval  25 (RMSECV = 0.005805, nLV = 3)
## Iteration  16/ 30... selected interval  18 (RMSECV = 0.005804, nLV = 3)
## Iteration  17/ 30... selected interval   2 (RMSECV = 0.005788, nLV = 3)
## Iteration  18/ 30... selected interval  30 (RMSECV = 0.005770, nLV = 3)
## Iteration  19/ 30... selected interval  16 (RMSECV = 0.005765, nLV = 3)
## Iteration  20/ 30... no improvements, stop.</code></pre>
<p>As you can see, by default method shows information for every step on the console. Use parameter <code>silent = TRUE</code> to change this behaviour. From the example above we can see that the global model had <span class="math inline">\(RMSECV = 0.005880\)</span> with 3 components. Creating local models with individual intervals gave the best performance with <span class="math inline">\(RMSECV = 0.013965\)</span> (interval #9). Combination of the interval #9 with interval #13 (next step) gave <span class="math inline">\(RMSECV = 0.006588\)</span>. The small improvement was obtained for adding 18 more intervals giving final result with <span class="math inline">\(RMSECV = 0.005765\)</span>.</p>
<p>There are several ways to explore the iPLS results both graphycally and numerically. First of all, summary will show full information about the selected interval, including number of variables on both ends:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="forward-ipls.html#cb3-1"></a><span class="kw">summary</span>(m)</span></code></pre></div>
<pre><code>## 
## iPLS variable selection results
##   Method: forward
##   Validation: venetian blinds with 10 segments
##   Number of intervals: 30
##   Number of selected intervals: 19
##   RMSECV for global model: 0.005880 (3 LVs)
##   RMSECV for optimized model: 0.005765 (3 LVs)
## 
## Summary for selection procedure:
##     n start end selected nComp        RMSE    R2
## 1   0     1 150    FALSE     3 0.005879630 0.958
## 2   9    41  45     TRUE     3 0.013965219 0.761
## 3  13    61  65     TRUE     4 0.006587547 0.947
## 4  21   101 105     TRUE     4 0.006105813 0.954
## 5   7    31  35     TRUE     3 0.006001804 0.956
## 6   5    21  25     TRUE     3 0.005957203 0.957
## 7  22   106 110     TRUE     3 0.005919741 0.957
## 8  19    91  95     TRUE     3 0.005897601 0.957
## 9  12    56  60     TRUE     3 0.005863754 0.958
## 10 11    51  55     TRUE     3 0.005836671 0.958
## 11 20    96 100     TRUE     3 0.005823808 0.958
## 12 26   126 130     TRUE     3 0.005819005 0.959
## 13  1     1   5     TRUE     3 0.005814690 0.959
## 14 14    66  70     TRUE     3 0.005810749 0.959
## 15 27   131 135     TRUE     3 0.005807191 0.959
## 16 25   121 125     TRUE     3 0.005804897 0.959
## 17 18    86  90     TRUE     3 0.005803532 0.959
## 18  2     6  10     TRUE     3 0.005787728 0.959
## 19 30   146 150     TRUE     3 0.005770345 0.959
## 20 16    76  80     TRUE     3 0.005765356 0.959</code></pre>
<p>Also you can see the first step (performance of individual models) and the selected interval by using function <code>plot()</code> for the whole model:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="forward-ipls.html#cb5-1"></a><span class="kw">plot</span>(m)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>You can also see the improvements of RMSECV graphycally:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="forward-ipls.html#cb6-1"></a><span class="kw">plotRMSE</span>(m)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Dashed line in this case shows RMSECV value for the global model with all intervals included.</p>
<p>Fnally you can get both seleced intervals and corresponding indices of variables (all of them not just interval limits) as follows:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="forward-ipls.html#cb7-1"></a><span class="kw">show</span>(m<span class="op">$</span>int.seleted)</span></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="forward-ipls.html#cb9-1"></a><span class="kw">show</span>(m<span class="op">$</span>var.selected)</span></code></pre></div>
<pre><code>##  [1]   1   2   3   4   5   6   7   8   9  10  21  22  23  24  25  31  32
## [18]  33  34  35  41  42  43  44  45  51  52  53  54  55  56  57  58  59
## [35]  60  61  62  63  64  65  66  67  68  69  70  76  77  78  79  80  86
## [52]  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103
## [69] 104 105 106 107 108 109 110 121 122 123 124 125 126 127 128 129 130
## [86] 131 132 133 134 135 146 147 148 149 150</code></pre>
<p>Also the model object contains the initial global model for full data (<code>m$gm</code>) and final PLS model made for the all selected data, <code>m$om</code>. In the following example I compare RMSE plots for both:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="forward-ipls.html#cb11-1"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb11-2"><a href="forward-ipls.html#cb11-2"></a><span class="kw">plotRMSE</span>(m<span class="op">$</span>gm)</span>
<span id="cb11-3"><a href="forward-ipls.html#cb11-3"></a><span class="kw">plotRMSE</span>(m<span class="op">$</span>om)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="interval-pls.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="backward-ipls.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 1
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
